sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t mukesh/docker_project -f Dockerfile.dev .

script:
  - docker run -e CI=true mukesh/docker_project npm run test
